name: RT

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test suite

    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - name: Install deps
        run: |
          sudo apt-get install protobuf-compiler python3 -y
          protoc --version
          python --version
          go get google.golang.org/protobuf/cmd/protoc-gen-go google.golang.org/grpc/cmd/protoc-gen-go-grpc
        env:
          GO111MODULE: on

      - name: Compile protos
        run: |
          python3 protos.py
        working-directory: rt

      - name: Run tests
        run: |
          go test
        working-directory: rt
