name: Worker

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test suite

    strategy:
      matrix:
        rust: [stable, nightly]

    steps:
      - uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}

      - name: Install protoc
        run: |
          sudo apt-get install protobuf-compiler -y
          protoc --version

      - name: Install test-all-features
        run: cargo install cargo-all-features

      - name: Check all features
        run: |
          cargo +${{ matrix.rust }} check-all-features
        working-directory: worker
        env:
          SQLX_OFFLINE: true

      - name: Run tests
        run: |
          cargo +${{ matrix.rust }} test --benches
        working-directory: worker
        env:
          RUST_LOG: caolo_sim=trace
          RUST_BACKTRACE: 1
          CARGO_INCREMENTAL: 0
          RUSTDOCFLAGS: "-Cpanic=abort"
          SQLX_OFFLINE: true

  clippy_check:
    runs-on: ubuntu-latest
    name: Clippy check
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy
          override: true

      - name: Install protoc
        run: |
          sudo apt-get install protobuf-compiler -y
          protoc --version

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --manifest-path ./worker/Cargo.toml
        env:
          SQLX_OFFLINE: true
